/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbountAfter: typeof import('./src/components/about/AbountAfter.vue')['default']
    AbountServices: typeof import('./src/components/about/AbountServices.vue')['default']
    AbountTeam: typeof import('./src/components/about/AbountTeam.vue')['default']
    AboutBanner: typeof import('./src/components/about/AboutBanner.vue')['default']
    AboutProjects: typeof import('./src/components/about/AboutProjects.vue')['default']
    ArticleBanner: typeof import('./src/components/articles/ArticleBanner.vue')['default']
    ArticleCarousel: typeof import('./src/components/articles/ArticleCarousel.vue')['default']
    ArticleList: typeof import('./src/components/articles/ArticleList.vue')['default']
    ArticlesList: typeof import('./src/components/articles/ArticlesList.vue')['default']
    BrandsGallery: typeof import('./src/components/home/BrandsGallery.vue')['default']
    CardsGallery: typeof import('./src/components/home/CardsGallery.vue')['default']
    HeroBanner: typeof import('./src/components/home/HeroBanner.vue')['default']
    HeroBrands: typeof import('./src/components/home/HeroBrands.vue')['default']
    HeroCards: typeof import('./src/components/home/HeroCards.vue')['default']
    HeroContact: typeof import('./src/components/home/HeroContact.vue')['default']
    HeroParallax: typeof import('./src/components/home/HeroParallax.vue')['default']
    HeroPricing: typeof import('./src/components/home/HeroPricing.vue')['default']
    HeroProjects: typeof import('./src/components/home/HeroProjects.vue')['default']
    JustifiedGallery: typeof import('./src/components/home/JustifiedGallery.vue')['default']
    ParallaxPage: typeof import('./src/components/common/ParallaxPage.vue')['default']
    RollingGallery: typeof import('./src/components/about/RollingGallery.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeoArticle: typeof import('./src/components/seo/SeoArticle.vue')['default']
    SeoBanner: typeof import('./src/components/seo/SeoBanner.vue')['default']
    SeoCarousel: typeof import('./src/components/seo/SeoCarousel.vue')['default']
    SeoList: typeof import('./src/components/seo/SeoList.vue')['default']
    SiteFooter: typeof import('./src/components/SiteFooter.vue')['default']
    SiteHeader: typeof import('./src/components/SiteHeader.vue')['default']
    WorksBanner: typeof import('./src/components/works/WorksBanner.vue')['default']
    WorksList: typeof import('./src/components/works/WorksList.vue')['default']
  }
}
